//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertisement_vistedlog
    {
    
    
    
    [EntityPrimKey("advertisement_vistedlog")]
        public long Id { get; set; }
    
    
    
        public int AdvertisementId { get; set; }
    
    
    
        public System.DateTime VistedDate { get; set; }
    
    
    
        public long ShowTimes { get; set; }
    
    
    
        public long ClickTimes { get; set; }
    
        public virtual advertisement advertisement { get; set; }
    }
}
