//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class advertisement
    {
        public advertisement()
        {
            this.advertisement_vistedlog = new HashSet<advertisement_vistedlog>();
        }
    
    
    
    
    [EntityPrimKey("advertisement")]
        public int Id { get; set; }
    
    
    
        public string AdName { get; set; }
    
    
    
        public string Code { get; set; }
    
    
    
        public int Width { get; set; }
    
    
    
        public int Height { get; set; }
    
    
    
        public int AdType { get; set; }
    
    
    
        public System.DateTime BeginDate { get; set; }
    
    
    
        public System.DateTime EndDate { get; set; }
    
    
    
        public int WebsiteId { get; set; }
    
        public virtual advertisement_type advertisement_type { get; set; }
        public virtual ICollection<advertisement_vistedlog> advertisement_vistedlog { get; set; }
    }
}
