//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class article
    {
        public article()
        {
            this.article_contents = new HashSet<article_contents>();
            this.article_images = new HashSet<article_images>();
            this.article_keyword = new HashSet<article_keyword>();
            this.article_website = new HashSet<article_website>();
            this.comments = new HashSet<comment>();
        }
    
    
    
    
    [EntityPrimKey("article")]
        public long ID { get; set; }
    
    
    
        public string Title { get; set; }
    
    
    
        public string Description { get; set; }
    
    
    
        public int CategoryId { get; set; }
    
    
    
        public string Author { get; set; }
    
    
    
        public System.DateTime PublishedDate { get; set; }
    
    
    
        public string ArticleSource { get; set; }
    
    
    
        public string SourceUrl { get; set; }
    
    
    
        public bool IsImageAticle { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<article_contents> article_contents { get; set; }
        public virtual ICollection<article_images> article_images { get; set; }
        public virtual ICollection<article_keyword> article_keyword { get; set; }
        public virtual ICollection<article_website> article_website { get; set; }
        public virtual ICollection<comment> comments { get; set; }
    }
}
