//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class base_user
    {
        public base_user()
        {
            this.base_user_role = new HashSet<base_user_role>();
        }
    
    
    
    
    [EntityPrimKey("base_user")]
        public int Id { get; set; }
    
    
    
        public string UserName { get; set; }
    
    
    
        public string Password { get; set; }
    
    
    
        public string Email { get; set; }
    
    
    
        public string Mobile { get; set; }
    
    
    
        public System.DateTime LastLoginTime { get; set; }
    
    
    
        public System.DateTime CreateDate { get; set; }
    
    
    
        public string HashCode { get; set; }
    
        public virtual ICollection<base_user_role> base_user_role { get; set; }
    }
}
