//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public category()
        {
            this.articles = new HashSet<article>();
            this.website_category = new HashSet<website_category>();
        }
    
    
    
    
    [EntityPrimKey("category")]
        public int Id { get; set; }
    
    
    
        public string CateName { get; set; }
    
    
    
        public string Description { get; set; }
    
    
    
        public string PingYin { get; set; }
    
    
    
        public bool IsEnabled { get; set; }
    
        public virtual ICollection<article> articles { get; set; }
        public virtual ICollection<website_category> website_category { get; set; }
    }
}
