//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
    
    
    
    [EntityPrimKey("comment")]
        public long Id { get; set; }
    
    
    
        public long ArticleId { get; set; }
    
    
    
        public string CommentContent { get; set; }
    
    
    
        public int WebsiteId { get; set; }
    
    
    
        public System.DateTime CommentTime { get; set; }
    
    
    
        public string IpAddress { get; set; }
    
    
    
        public bool IsPublish { get; set; }
    
        public virtual article article { get; set; }
        public virtual website website { get; set; }
    }
}
