//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<operate_log> operate_log { get; set; }
        public virtual DbSet<sequence> sequences { get; set; }
        public virtual DbSet<sys_user> sys_user { get; set; }
        public virtual DbSet<user> users { get; set; }
        public virtual DbSet<city> cities { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<project_case> project_case { get; set; }
        public virtual DbSet<sys_dictionary> sys_dictionary { get; set; }
    }
}
