//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.images = new HashSet<image>();
        }
    
    
    
    
    [EntityPrimKey("product")]
        public int id { get; set; }
    
    
    
        public string product_name { get; set; }
    
    
    
        public string product_desc { get; set; }
    
    
    
        public string country { get; set; }
    
    
    
        public string amazon_url { get; set; }
    
    
    
        public Nullable<int> main_image_id { get; set; }
    
    
    
        public Nullable<int> categoryid { get; set; }
    
    
    
        public string product_specification { get; set; }
    
    
    
        public string product_features { get; set; }
    
    
    
        public string seo_title { get; set; }
    
    
    
        public string seo_keyword { get; set; }
    
    
    
        public string seo_desc { get; set; }
    
    
    
        public Nullable<int> is_publish { get; set; }
    
    
    
        public string germany_amazon_url { get; set; }
    
    
    
        public string franch_amazon_url { get; set; }
    
    
    
        public string Italy_amazon_url { get; set; }
    
    
    
        public string spanish_amazon_url { get; set; }
    
    
    
        public string japan_amazon_url { get; set; }
    
    
    
        public string uk_amazon_url { get; set; }
    
        public virtual category category { get; set; }
        public virtual ICollection<image> images { get; set; }
        public virtual image image { get; set; }
    }
}
