//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class spider_content
    {
    
    
    
    [EntityPrimKey("spider_content")]
        public long Id { get; set; }
    
    
    
        public string Title { get; set; }
    
    
    
        public string Description { get; set; }
    
    
    
        public string HtmlContent { get; set; }
    
    
    
        public string TextContent { get; set; }
    
    
    
        public string SourceUrl { get; set; }
    
    
    
        public System.DateTime ExpiredDate { get; set; }
    
    
    
        public int CategoryId { get; set; }
    }
}
