//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
    
    
    
    [EntityPrimKey("user")]
        public int Id { get; set; }
    
    
    
        public string user_name { get; set; }
    
    
    
        public string real_name { get; set; }
    
    
    
        public string qq_number { get; set; }
    
    
    
        public string phone { get; set; }
    
    
    
        public string mobile { get; set; }
    
    
    
        public string email { get; set; }
    
    
    
        public string photo_path { get; set; }
    
    
    
        public string password { get; set; }
    
    
    
        public string hash_code { get; set; }
    
    
    
        public Nullable<int> position_id { get; set; }
    
    
    
        public Nullable<int> is_admin { get; set; }
    
    
    
        public Nullable<int> company_id { get; set; }
    
    
    
        public string login_token { get; set; }
    
    
    
        public Nullable<System.DateTime> last_login_time { get; set; }
    
    
    
        public Nullable<System.DateTime> create_time { get; set; }
    
    
    
        public Nullable<System.DateTime> update_time { get; set; }
    }
}
