//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebCenter.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class website
    {
        public website()
        {
            this.article_website = new HashSet<article_website>();
            this.comments = new HashSet<comment>();
            this.visited_log = new HashSet<visited_log>();
            this.website_category = new HashSet<website_category>();
            this.website_setting = new HashSet<website_setting>();
        }
    
    
    
    
    [EntityPrimKey("website")]
        public int Id { get; set; }
    
    
    
        public string Name { get; set; }
    
    
    
        public string SiteNameCn { get; set; }
    
    
    
        public string SiteNameEn { get; set; }
    
    
    
        public string SiteUrl { get; set; }
    
    
    
        public System.DateTime CreateTime { get; set; }
    
    
    
        public System.DateTime UpdateTime { get; set; }
    
        public virtual ICollection<article_website> article_website { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<visited_log> visited_log { get; set; }
        public virtual ICollection<website_category> website_category { get; set; }
        public virtual ICollection<website_setting> website_setting { get; set; }
    }
}
